apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-java
  name: user-java-service
  namespace: jacob-lichty
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: user-java